#! /bin/sh

### BEGIN INIT INFO
# Provides:          dev-starter
# Required-Start:    $network
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: 
# Description: 
### END INIT INFO

case "$1" in
  start)
    /vagrant/dev-starter-script start
    ;;
  stop)
    /vagrant/dev-starter-script stop
    ;;
  *)
    echo "Usage: service dev-starter {start|stop}" >&2
    exit 1
    ;;
esac

exit 0
