# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d08092f573f0c877b6c2ef4e289f4374846b865fe449bf5d8b89dc7630dd41cddcbbcf2674eecfc3e77bd74503055dee1ee8a9a8f3a38d8c7ef69e11137e405

test:
  secret_key_base: 2459f36c3844df2a68949d938268923dc83008a1a5a10a94a07666d12fcd767ce7f7e8c3c842c774174e154a4dc009475411d268634daa5e015e99745abf04fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
